### PR TITLE
Dependency config snippet

### LINKED ISSUE #110: Provide copy/pastable snippet on package page for mix.exs entry
It could be for the latest version, i.e.: If I'm viewing httpoison's hex.pm page, I could have a snippet:

    {:httpoison, "~> 0.6"}

That is for the latest major version. Thoughts?

### PR DESCRIPTION
**Pull request by Tuxified**
Fixes #110 :

- add snippet for mix & rebar config
- upgraded bootswatch version (so I could use glyphicons)
- added copy button (works in Chrome, FF < 41, Safari don't support it, untested in IE etc)

~~There was no tooltip lib, since it didn't want to introduce new deps I made a crude 'copy' animation~~ Tooltip added

### CODE REVIEW

**Comment by ericmj** [comment]
This looks good we just need to tweak the configs slightly. For rebar we should give a strict version: `{my_package, "1.2.3"}` because rebar doesn't support `*` in the version string.

We also need to handle the case when the OTP application name != package name. For mix it should be `{:my_app, "~> ...", hex: :my_package}`. For rebar `{my_app, "...", {pkg, my_package}}`.

**Comment by ericmj** [comment]
I also just noticed that the copy button moves down 1 pixel when I mouse over it.

**Comment by Tuxified** [comment]
Hmm... how do I find out out what the name for the OTP application is? I don't see it in the schema / models ?

**Comment by ericmj** [comment]
`release.meta["app"]` will return the OTP application name.

**Comment by Tuxified** [comment]
@ericmj any remarks? FYI: starting tomorrow I'll be away for a few days, in case something needs to be addressed

**Comment by ericmj** [comment]
Thanks for your work @Tuxified. Seems the button still moves on hover, will try to fix locally.

**Pull request merged**
