### PR TITLE
Word-wrap long package names

### LINKED ISSUE #453: Word-wrap long package names
See:

- https://hex.pm/packages/nerves_system_qemu_arm - see dependencies
- https://hex.pm/packages/nerves_toolchain_arm_unknown_linux_gnueabihf - see package name at the top

### PR DESCRIPTION
**Pull request by sotojuan**
Closes #453.

[Preview](http://i.imgur.com/IXxbrdc.png).

### CODE REVIEW

**Comment by ericmj** [comment]
Do you think we can wrap the dependency name so that the version requirement shows up on the same line?

**Comment by sotojuan** [comment]
Hm, I'm no CSS whiz so not sure—let me play around with it for a bit.

**Comment by sotojuan** [comment]
Hey @ericmj, I can't seem to get what you want, sorry. Would you still merge this? I'll keep the fix in mind and will push a PR if I ever come across it. If not, I can give it some more time!

**Comment by ericmj** [comment]
@sotojuan Thanks for trying!

**Pull request merged**
