### PR TITLE
Enable syntax highlighting for doc code blocks

### PR DESCRIPTION
**Pull request by jcspencer**
This PR uses [highlight.js](https://highlightjs.org) to highlight the Elixir and Erlang syntax in the documentation.

### CODE REVIEW

**Comment by jcspencer** [comment]
Demo:
demo

**Comment by ericmj** [comment]
Beautiful! Thank you.

**Comment by ericmj** [comment]
Do you know if the highlight error of `defp` is reported to highlight.js?

**Comment by jcspencer** [comment]
Not that I know of.. that's a strange issue. I'll look into it.

**Comment by jcspencer** [comment]
The issue looks to be that the elixir highlighting code is not included in the default highlight.js bundle, and is defaulting to Ruby.

I've pushed a fix that includes a custom highlight.js bundle with *only* erlang and elixir support.

**Pull request merged**
