### PR TITLE
Don't render layout twice for error pages

### PR DESCRIPTION
**Pull request by wojtekmach**
See: https://hex.pm/packages/404

### CODE REVIEW

**Comment by ericmj** [comment]
This unfortunately removes the layout when rendering raised exceptions. See this discussion: https://github.com/hexpm/hex_web/issues/223.

**Comment by wojtekmach** [comment]
yeah, I just saw that my patch would break on e.g.: localhost:4000/404. From what I got from the discussion it seems like you're gonna go with https://github.com/phoenixframework/phoenix/issues/1504#issuecomment-180773900 but if I can help in any other way/in the meantime - just let me know

**Comment by ericmj** [comment]
Can amend the PR to instead add `put_layout(false)` as shown in the linked issue?

**Comment by wojtekmach** [comment]
@ericmj sure, I'm on it

**Comment by wojtekmach** [comment]
@ericmj done, I think it's ready. I tested this on:
- http://localhost:4000/404
- http://localhost:4000/packages/404
- http://localhost:4000/packages (I hardcoded index action to raise an error and observed it rendering the error template)

**Comment by ericmj** [comment]
@wojtekmach It needs to be added everywhere we render the errorview.

**Comment by wojtekmach** [comment]
@ericmj yeah, I thought about that. From what I saw the places it might be needed are:

```
~/src/vendor/hex_web[fix_error_page]% ag ErrorView lib web/
lib/hex_web/rate_limit.ex
104:          |> render(HexWeb.ErrorView, :"422", message: "API rate limit exceeded for #{ip_str(ip)}")

web/controllers/auth_helpers.ex
75:    |> render(HexWeb.ErrorView, :"401", message: reason)
82:    |> render(HexWeb.ErrorView, :"403", message: reason)

web/controllers/controller_helpers.ex
40:    |> render(HexWeb.ErrorView, :"422", errors: errors)
58:    |> render(HexWeb.ErrorView, :"404")
```

and all the places except for the last one (which this PR is changing) are only used by API requests where the layout is not needed anyway. I don't mind adding it in all places though if you prefer, it's an easy change

**Comment by ericmj** [comment]
Please add it to all places or extract the calls to render errorview to a function. It is easy to accidentally use an error function, that doesn't remove the layout, in the wrong place.

**Comment by wojtekmach** [comment]
@ericmj ok, sounds good :+1:. I think I'll extract common code into something like: `HexWeb.ControllerHelpers.render_error(status, template, assigns`

**Comment by wojtekmach** [comment]
@ericmj I think this is ready, please let me know if this could be improved or if I missed anything.

btw, I noticed that RateLimit plug isn't tested, so I tested the change on that plug manually and it seems to work well. I can later tackle adding a test for rate limit in another PR

**Comment by ericmj** [comment]
Perfect, thank you!

> I can later tackle adding a test for rate limit in another PR

Please do :+1:

**Pull request merged**
