### PR TITLE
Add user page that shows user's packages

### PR DESCRIPTION
**Pull request by ma2gedev**
There are many awesome packages in hex.pm.
I would like to know creators who created awesome packages like rubygems.org profile page (e.g. https://rubygems.org/profiles/josevalim). :smiley:
This pull request adds creator specific page that shows user's packages.

## main changes
- user page uri is `/users/:id` for example `/users/100`
- add user page link into `/packages/:name` page

## after this pull request

- package page shows user page links

- user page shows user's package

### CODE REVIEW

**Comment by josevalim** [comment]
Nice!

**Comment by ericmj** [comment]
Thanks @ma2gedev. I appreciate the hard work and Hex needs all help it can get but I don't think we can accept this PR unfortuntely.

The only reason we have users at all in Hex is because it's the easiest to make sure only the package owner(s) can publish the package. We never show who owns the package because that is private information, if the maintainers want they can list this information themselves on the package page either through links (to the github repo for example) or by listing themselves in the contributors field.

The API also hides the information: /api/users/:email_or_username returns 404 for everyone but the currently authed user so you can see we already hide this information.

**Comment by teamon** [comment]
@ericmj Can you elaborate a bit more about the reasoning? I'm not saying it's bad, I'm just curious.

**Comment by josevalim** [comment]
@teamon the reasoning is clear above: all the user information we have on the website today is private. There are no plans to make it public. The links section is a great opportunity to expand on that if someone wants to.

**Comment by ma2gedev** [comment]
Thanks everyone to explain background about user information.
I understood the reason why this PR is not accepted. I'll close it.

Also thanks for all your work!

**Comment by teamon** [comment]
Well, right, actually makes sense, thanks! :)

**Pull request closed without merging**
