### PR TITLE
Add Trending and Awesomeness sections to Homepage

### PR DESCRIPTION
**Pull request by Blackrush**
#### Disclaimer

I am a junior Elixir and French-speaking developer. Every English mistakes is involuntary and should be emphasized :smiley: 

This pull-request adds Trending and Awesomeness sections giving more insight on Elixir project.

* Trending : It shows the last 10 most downloaded packages of the week.
* Awesomeness : It shows the last added packages to h4cc/awesome-elixir awesome list. Data is fetched from Github API using HTTPoison, and cached for 24 hours using ConCache.

### New dependencies

* [HTTPoison](https://hex.pm/packages/httpoison)
* [ConCache](https://hex.pm/packages/con_cache)

### CODE REVIEW

**Comment by vendethiel** [comment]
> I am a junior Elixir and French-speaking developer. Every English mistakes is involuntary and should be emphasized

I will make sure to thorougly punish him for that, of course ;-).

Otherwise, nice job!

**Comment by ericmj** [comment]
The list of "awesome" projects fetched from awesome-elixir seems to just be added by a job that automatically adds projects when they are published to hex.pm. Additionally we should not depend on an external project.

We can show trending packages but then we should remove total package downloads.

**Comment by Blackrush** [comment]
Or maybe a tab displaying total, week, and day downloads?

**Comment by ericmj** [comment]
I don't want an extra tab for just 3 stats. The stats page would show less stats than the front page. Just showing weekly downloads is fine.

**Comment by ericmj** [comment]
Ping?

**Comment by Blackrush** [comment]
Sorry I completely forgot about this pull-request.

I didn't find any "stats" page as you mentioned previously. Otherwise I quite didn't get what you wanted.

**Comment by ericmj** [comment]
Sorry, I decided to just change the front page to weekly downloads instead of all time downloads. You can do the change in a separate PR or I will get to it soon. Thank you!

**Pull request closed without merging**
