### PR TITLE
[Fix #214] Set version for erlang.mk config

### LINKED ISSUE #214: No version set for erlang.mk config
The `@erlang_mk_snippet` variable here is never set https://github.com/hexpm/hex_web/commit/67fc985ec7e1f5096f849199341e5232e052d979#diff-1be7478849c2bf867887bec60dec003eR159.

/cc @elbrujohalcon

### PR DESCRIPTION
**Pull request by elbrujohalcon**
@ericmj hopefully this is enough, but even when tests pass for me I'm coding in half-blind mode here :scream:

### CODE REVIEW

**Comment by ericmj** [comment]
We have no tests for the HTML right now, it assumes you run the server and check the website.

**Comment by elbrujohalcon** [comment]
@ericmj and can you / would you do that for me? Or rather, do you have a db backup available I can use for testing because in my local instance there are, of course, no packages when I start the system :blush:

**Comment by ericmj** [comment]
Sure I can check it out.

You can fill your db with some sample data with `mix run scripts/sample_data.exs`.

**Comment by elbrujohalcon** [comment]
ups_14___hex

**Comment by ericmj** [comment]
:heart:

**Pull request merged**
