### PR TITLE
Fetch resources from CloudFlare CDN

### PR DESCRIPTION
**Pull request by JamesS237**
This PR simply pulls front end resources all from the same CDN, instead of several, therefore speeding up the page load time.
The CDN used is CloudFlare, which is extremely reliable and well distributed.

:car: :airplane:

### CODE REVIEW

**Comment by jeregrine** [comment]
Maybe we could put all of hex behind cloudflare?

**Comment by JamesS237** [comment]
The main issue with putting hex.pm behind CloudFlare is the pricing when it comes to SSL. Unless hex.pm switched to a CloudFlare-issued SSL certificate, it would $200 a month.

Currently, hexdocs.pm is behind CloudFlare, but it does not use SSL like hex.pm.

**Comment by josevalim** [comment]
How much it would cost if we switched to CloudFare SSL though?

**Comment by JamesS237** [comment]
CloudFlare Free would ultimately cover what we need. It would force us to use a CloudFlare issued SSL certificate that will work in [most modern browsers](https://www.cloudflare.com/ssl#browsers). Otherwise, a Pro plan ($20 per month) would be fine as well.

**Comment by ericmj** [comment]
Thanks!

**Pull request merged**
