### PR TITLE
Fixes HTML errors

### PR DESCRIPTION
**Pull request by jaimeiniesta**
This PR fixes some HTML errors detected with Validator.nu.

You can verify these changes on https://hex-web-jaimeiniesta.herokuapp.com/

### CODE REVIEW

**Comment by ericmj** [comment]
Seems to be a border-bottom added to all paragraphs.

**Comment by jaimeiniesta** [comment]
Fixed.

**Comment by ericmj** [comment]
Thank you!

**Comment by jaimeiniesta** [comment]
My pleasure!

**Pull request merged**
