### PR TITLE
Create initial download record when creating release. Fixes #360

### LINKED ISSUE #360: sort by download not display packages without downloads
After the publication of a package, I identified that if a package has no download, it is not listed in the results if the order is by number of downloads

https://hex.pm/packages?search=pagar&sort=downloads

image

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by ericmj** [comment]
I think this will create duplicate download records when we run the stats job. I think we should figure out why the sort query doesn't work correctly and fix that instead.

**Comment by wojtekmach** [comment]
> I think this will create duplicate download records when we run the stats job

we delete all records for a given date, before inserting new ones - see [stats_job.ex](https://github.com/hexpm/hex_web/blob/1dbf70d3dce857d96b88fe11172154e124b695ff/lib/hex_web/stats_job.ex#L55)

btw, how often do we run stats job?

> I think we should figure out why the sort query doesn't work correctly and fix that instead.

fair enough, I can see if we can change the query instead.

**Comment by ericmj** [comment]
> btw, how often do we run stats job?

Once every 24 hours.

**Comment by wojtekmach** [comment]
Closing in favor of #367

**Pull request closed without merging**
