### PR TITLE
Delete associated docs when reverting release

### LINKED ISSUE #85: Delete associated docs when reverting release

### PR DESCRIPTION
**Pull request by jcspencer**
Closes #85

This PR deletes the associated documentation of a release when it is reverted.

### CODE REVIEW

**Comment by ericmj** [comment]
Can you add a test?

**Comment by jcspencer** [comment]
@ericmj will do :+1:

**Comment by jcspencer** [comment]
@ericmj All done. Not sure if this one should be tagged `:integration`. Could you give me a heads up?

**Comment by ericmj** [comment]
@jcspencer Perfect! Just what I had in mind. Please tag with `:integration` and move the test to the bottom with the other docs test.

**Comment by jcspencer** [comment]
@ericmj Great; done! :+1:

**Comment by ericmj** [comment]
:heart:

**Pull request merged**
