### PR TITLE
Add section about user information to privacy policy

### PR DESCRIPTION
**Pull request by ericmj**
This change adds a dedicated section about what user information we store and what is public.

With this change we are also making the following information public that was previously private or not stored: the user's username, full name, email address and packages they own.

/cc @hexpm/contributors @hexpm/rebar3

### CODE REVIEW

**Comment by ericmj** [comment]
Based on feedback from @josevalim a note about opting out showing a public email address has been added.

Two weeks before the changes are made on hex.pm an email will be sent out informing all users about the privacy policy changes.

**Comment by ferd** [comment]
I agree with allowing an opt-out for e-mails. Makes sense, and a public email warning of the change is also good. 

Only thing I think is that within the doc, it *sounds* like the hashed password is part of the profile, and then you do say that the profile information will be public (but omit the hashed password as the data).

To me it's obvious the hashed password is not going to be made public; I'm just guessing qualifying it as 'profile information' is not super clear. That's very, very minor, and I wouldn't block on that though.

**Comment by ericmj** [comment]
> Only thing I think is that within the doc, it sounds like the hashed password is part of the profile, and then you do say that the profile information will be public (but omit the hashed password as the data).

That's a very good point. I will make the distinction more clear between profile information and privately stored information.

**Comment by ericmj** [comment]
Thanks for your feedback. Will send out notification email when website login is in production.

**Pull request merged**
