### PR TITLE
Added hexer and hexer.mk tools to index.html.eex file

### PR DESCRIPTION
**Pull request by davecaos**

### CODE REVIEW

**Comment by ericmj** [comment]
It seems like this tool is only for publishing packages, on the front page we show how to consume packages - not how to publish them.

**Comment by elbrujohalcon** [comment]
@ericmj Aren't most of the tasks provided by the rebar3_hex plugin also for publishing packages? I think the only one not _publish-related_ is [search](http://www.rebar3.org/v3.0/docs/hex-package-management#search). To consume packages you don't actually use `rebar3_hex`, you just use `rebar3`. Or am I missing something?

**Comment by ericmj** [comment]
@elbrujohalcon That's true, we should tweak the rebar example to match the elixir one. Although it already talks about how to install rebar.

**Comment by josevalim** [comment]
Really neat to know about hexer and hexer.mk. I agree with the sentiment here: the home page should focus on consuming packages. We can talk on other tools in other sections.

**Comment by jcspencer** [comment]
Possibly a 'third-party tooling' or 'third-party projects' section? 

On 18 December 2015 1:04:25 AM GMT+07:00, "José Valim" <notifications@github.com> wrote:
>Really neat to know about hexer and hexer.mk. I agree with the
>sentiment here: the home page should focus on consuming packages. We
>can talk on other tools in other sections.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/pull/199#issuecomment-165533652

-- 
James Spencer

**Comment by tsloughter** [comment]
Good point. Should change the rebar3 one to just show that you put `{pkg, vsn}` in the `deps` list of `rebar.config` for use with rebar3.

**Comment by ericmj** [comment]
Closing this due to previous discussion. If have a way to consume to packages please send a new PR so we can add that to the frontpage.

@tsloughter Can you fix the rebar3 text?

**Comment by tsloughter** [comment]
Will do.

**Pull request closed without merging**
