### PR TITLE
New frontend

### PR DESCRIPTION
**Pull request by ericmj**
#### TODO:

* [x] Make logo look better, black text on dark grey is not ideal and the image needs to be scaled up
* [x] Provide higher resolution images, they currently look blurry on retina
* [x] Center and align stats
* [x] ~~Add actual links in "getting started" section on frontpage~~
* [x] Fix styling of package paginator
* [x] Fix styling of version expand button on package page
* [x] Add search box to header
* [x] Fix anchors on docs page, the fixed header covers the anchor
* [x] Make footer stick to the bottom
* [x] Hide letters when displaying search results
* [x] Final rebase

Here you can see a live read-only version of the new frontend design: https://hexpm-frontend.herokuapp.com

We also need to make sure the website looks good on small screens but it's not needed for the first release.

### CODE REVIEW

**Comment by ericmj** [comment]
If you find any issues with the new frontend please let us know and I will add it to the TODO.

**Comment by wojtekmach** [comment]
it's more like an additional feature than bug with the redesign, but I think it would be good if packages search page would have the search box again (ideally with pre-filled search query) which would help discovering packages and correcting typos in search query. See [old](https://hex.pm/packages?_utf8=✓&search=ecto&sort=downloads) vs [new](https://hexpm-frontend.herokuapp.com/packages?search=ecto&sort=downloads)

**Comment by wojtekmach** [comment]
minor bug: fix anchors on docs page. See: https://hexpm-frontend.herokuapp.com/docs/tasks#hex_build - the "hex.build" section of the docs page is not visible. It's a common problem with fixed header and anchors.

**Comment by ericmj** [comment]
@wojtekmach Added your suggestions to the todo.

**Comment by Gazler** [comment]
Maybe we should use different icons for the downloads instead of 3 calendars? I have attached one idea I had below.

hex-icons-new

**Comment by ericmj** [comment]
I think we can have slightly different icons but those are very different for essentially the same thing.

**Comment by pragmaticivan** [comment]
@ericmj can you update the list of tasks already finished.

**Comment by ericmj** [comment]
@pragmaticivan Updated

**Comment by wojtekmach** [comment]
@pragmaticivan @ericmj what did you have in mind for the Getting started section? There're 3 links on the mockups: installing, screencasts & docs, and community. Would they link to some existing pages, or new pages? If we don't yet have new pages, I'd propose to just make "Getting started" a link pointing to https://hexpm-frontend.herokuapp.com/docs/usage, and remove the remaining links.

**Comment by ericmj** [comment]
@wojtekmach I'm not sure yet actually. Only one link would look weird, we need around 3 links. Linking to usage only for the mix client is a bit unfair to the other clients also.

**Comment by wojtekmach** [comment]
Yeah, I agree. What do you think about dropping that section for now (until we have more content to fill in) and instead make "Using with Elixir" and "Using with Erlang" clickable, pointing to mix/rebar3 usage docs?

**Comment by ericmj** [comment]
@wojtekmach Sounds good!

**Comment by ericmj** [comment]
I'm a complete SCSS noob, does anyone know how to clean up these media queries? https://github.com/hexpm/hex_web/pull/285/commits/980781592a0bd30dce05be5e42957368cf8cf0b8#diff-264176f47fe2988b561236934df0497dR117

**Comment by wojtekmach** [comment]
since we're already using SCSS we should also use variables to DRY up stuff, colors in particular.

**Comment by ericmj** [comment]
> since we're already using SCSS we should also use variables to DRY up stuff, colors in particular.

Definitely, if you find anything, please send PRs :)

**Comment by wojtekmach** [comment]
Sure! Just pointing it out in case people are looking for easy
contributions :) I'll likely pick it up later

2016-04-17 0:03 GMT+02:00 Eric Meadows-Jönsson <notifications@github.com>:

> since we're already using SCSS we should also use variables to DRY up
> stuff, colors in particular.
>
> Definitely, if you find anything, please send PRs :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex_web/pull/285#issuecomment-210912786>
>



-- 
Wojtek Mach

**Comment by pragmaticivan** [comment]
screen shot 2016-04-16 at 4 51 15 pm

If we move this purple line we can automatically get a nice responsible layout, that was the last approach I was moving to start the responsive part of this layout.

**Comment by pragmaticivan** [comment]
By the way, Nice job guys!!! That looks super exciting!

**Comment by pragmaticivan** [comment]
screen shot 2016-04-16 at 8 05 51 pm
Not having the download count for New Packages and Recently Updated seems to not align in a good way. Solution: remove 2 or Most Downloaded or Add limit for 12 in new packages and recently updated.

**Comment by ericmj** [comment]
> Not having the download count for New Packages and Recently Updated seems to not align in a good way. Solution: remove 2 or Most Downloaded or Add limit for 12 in new packages and recently updated.

Agreed. The downloads text is too prominent also, it could be made smaller. It also seems the description can go to two lines sometimes also, see ecto for example, it should be capped to a single line.

**Comment by ericmj** [comment]
I think we are ready to rebase against master and release. If anyone have any changes they want to get in before please let me know since this branch will be rebased and history will get weird if you make changes during that.

Huge thanks to everyone who has helped out and an extra big thank you to @pragmaticivan who made the design. :heart:

**Pull request merged**
